name: smart_diet
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter 
  freezed_annotation: ^2.4.1 # Mimari
  json_annotation: ^4.8.1 # Mimari
  flutter_gen: ^5.4.0  # Mimari
  flutter_svg: ^2.0.9 
  lottie: ^2.7.0
  kartal: ^3.5.0
  google_fonts: ^6.1.0
  gap: ^3.0.1 
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.4
  form_builder_validators: ^9.1.0 
  introduction_screen: ^3.1.12 
  flutter_form_builder: ^9.2.1
  image_picker: ^1.1.1
  easy_rich_text: ^2.1.0
  dropdown_search: ^5.0.6
  firebase_core: ^2.30.1 # Firebase
  cloud_firestore: ^4.17.2 # Firebase
  firebase_auth: ^4.19.4 # Firebase
  flex_color_scheme: ^7.3.1 
  shared_preferences: ^2.2.3
  persistent_bottom_nav_bar_v2: ^5.2.3
  fluttermoji: ^1.0.2
  awesome_dialog: ^3.2.1
  table_calendar: ^3.0.9   
  tflite_v2: ^1.0.0 # Tensorflow Lite
  intl: ^0.18.1 
  group_radio_button: ^1.3.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  very_good_analysis: ^5.1.0

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lotties/
    - assets/images/ 
    - assets/model/
    
flutter_gen: 
  output: lib/common/gen/
  integrations: 
    flutter_svg: true
    lottie: true 
  assets: 
    enabled: true
  colors: 
    inputs: 
      - assets/colors/colors.xml
      - assets/colors/tailwind.xml
    enabled: true
  line_length: 80

